#!/bin/bash

####### String Userid
USER=`whoami`

#### Start Date
Start_Date=`date +%Y/%m/%d" "%H:%M:%S`

####### Storing this process id.
RPID=$$ 

## Define the Elasticsearch connection object
elasticHost="elastic.example.com:9200"

## As using $@ will tell all the arguments passed to this wrapper.
FullCommand=`echo $@`

## Define the GNU Time Format output here as TMF    
## This Statement is prepared so that it can directly used as elasticsearch url string

#TMF="update cron_jobs SET cpu='%P', ert='%e', exit_status='%x', end_time=now() where id=$LastInsertId"
TMP="{"hostname":"$HOSTNAME", 

#### Passing all the arguments to this script to time command Using the format TMF , Output will be sent to the file named as processid of this script####
/usr/bin/time -f "$TMF" -o /tmp/$RPID $@


## Finalyy removing the mess crested by this wrapper
rm -f /tmp/$RPID > /dev/null 2>&1

#### Start Date
Start_Date=`date +%Y/%m/%d" "%H:%M:%S`

{"title":"test1", "text":"testweb1", "date":"2014/04/04"}
curl -H "Accept: application/json" -H "Content-type: application/json" -X POST -d '{"title":"test1", "text":"testweb2", "date":"2014/04/04"}' http://localhost:9200//website/blog/


himanshu@foonix1:~$ echo '{"hostname": "asd", "cpu": "%P", "avg_mem": "%K", "page_faults": "%F", "ert": "%e"}' | python -m json.tool
{
    "avg_mem": "%K",
    "cpu": "%P",
    "ert": "%e",
    "hostname": "asd",
    "page_faults": "%F"
}

